dtb-$(CONFIG_ARCH_FSL_IMX8MM) += \
	fsl-imx8mm-sue-stream195x-l0-kit.dtb \
	fsl-imx8mm-sue-stream195x-l0-factory.dtb \
	fsl-imx8mm-sue-stream195x-emmc-l0-factory.dtb \
	fsl-imx8mm-sue-stream195x-emmc-l0-kit.dtb

always		:= $(dtb-y)
clean-files	:= *.dtb
