# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MESON) += axg_sue_s1832_l1_prime.dtb
dtb-$(CONFIG_ARCH_MESON) += axg_sue_s1832_l2_prime.dtb
dtb-$(CONFIG_ARCH_MESON) += axg_sue_s1832_l1_factory.dtb
dtb-$(CONFIG_ARCH_MESON) += axg_sue_s1832_l2_factory.dtb
dtb-$(CONFIG_ARCH_MESON) += axg_sue_s1832_l2_streamkit1832_dabfm.dtb
dtb-$(CONFIG_ARCH_MESON) += axg_sue_s1832_l2_streamkit1832_voice.dtb
